version: '3.4'
services:
    similewebgis:
        build:
            context: .
            args:
                NODE_ENV: development
        volumes:
            - ./:/usr/src/app
            - ./usr/src/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev