version: '3.4'
services:
    similewebgis:
        build:
            context: .
            args:
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        command: node app.js